# Generated by Django 3.2.12 on 2022-09-27 02:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('docentes', '0002_auto_20220927_0226'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Actividade',
            new_name='Actividad',
        ),
    ]
