# Generated by Django 3.2.12 on 2022-09-27 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docentes', '0003_rename_actividade_actividad'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentario',
            name='comentario',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='planeacion',
            name='check',
            field=models.BooleanField(default=False),
        ),
    ]
