# Generated by Django 4.1.1 on 2022-09-27 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docentes', '0007_auto_20220927_0314'),
    ]

    operations = [
        migrations.RenameField(
            model_name='planeacion',
            old_name='check',
            new_name='anonima',
        ),
        migrations.AddField(
            model_name='planeacion',
            name='finalizada',
            field=models.BooleanField(default=False),
        ),
    ]
