# Generated by Django 4.1.1 on 2022-09-27 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docentes', '0008_rename_check_planeacion_anonima_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='planeacion',
            name='observaciones',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='planeacion',
            name='tema',
            field=models.CharField(default='letras', max_length=60),
            preserve_default=False,
        ),
    ]
