# Generated by Django 4.1.1 on 2022-09-28 01:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('docentes', '0009_planeacion_observaciones_planeacion_tema'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favorito',
            name='votos',
        ),
    ]
