# Generated by Django 4.1.1 on 2022-09-28 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docentes', '0010_remove_favorito_votos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favorito',
            name='fecha_agregad',
            field=models.DateField(auto_now_add=True),
        ),
    ]
