# Generated by Django 4.1.1 on 2022-09-30 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docentes', '0012_actividad_finalizada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planeacion',
            name='observaciones',
            field=models.TextField(blank=True, null=True),
        ),
    ]
