# Generated by Django 4.1.1 on 2022-11-18 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docentes', '0013_alter_planeacion_observaciones'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actividad',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='comentario',
            name='comentario',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Rating',
        ),
    ]
